export const INITIAL_SERVICES = [
  // Bridal Packages
  {
    _id: "65a000000000000000000001",
    title: "Classic Bridal Package",
    price: "₹18,000",
    tagline: "Essential HD makeover for budget-conscious brides",
    description: "High Definition (HD) Foundation Base, Traditional Hair Styling & Flower Draping, Saree Box Pleating, Eyelash Extension, Studio Consultation.",
    imageUrl: "/images/portfolio/traditional-south-indian-bride.jpg",
    category: "bridal_package",
    ctaText: "Book Classic Package",
  },
  {
    _id: "65a000000000000000000002",
    title: "Royal HD Makeover Package",
    price: "₹25,000",
    tagline: "Our most popular 2-event Muhurtham + Reception package",
    description: "HD Base for Muhurtham & Reception, 2 Hairstyles, Premium Saree Pre-Pleating, Free Trial Session, Jewellery Discount, Mother Touch-Up.",
    imageUrl: "/images/portfolio/bridal-pink-saree-gold-jewellery.jpg",
    category: "bridal_package",
    ctaText: "Book Royal HD Package",
  },
  {
    _id: "65a000000000000000000003",
    title: "Luxury Airbrush Grand Package",
    price: "₹35,000",
    tagline: "18+ Hour waterproof Airbrush finish for grand stage weddings",
    description: "18-Hour Waterproof Airbrush Base, 3 Event Looks, Senior Hairstylist & Saree Team, Studio Trial, Temple Jewellery Included, 2 Family Touch-Ups.",
    imageUrl: "/images/portfolio/before-after-hd-makeover.jpg",
    category: "bridal_package",
    ctaText: "Book Luxury Airbrush",
  },
  // Makeup Services
  {
    _id: "65a000000000000000000004",
    title: "HD Sweat-Proof Bridal Makeup",
    price: "From ₹9,999",
    description: "Long-lasting high-definition pigments for camera clarity and natural skin finish.",
    imageUrl: "/images/portfolio/bridal-close-up-portrait.jpg",
    category: "makeup",
    ctaText: "Book HD Makeup",
  },
  {
    _id: "65a000000000000000000005",
    title: "Airbrush Waterproof Makeover",
    price: "From ₹12,999",
    description: "18+ hour stage-ready waterproof airbrush finish for heavy mandap heat.",
    imageUrl: "/images/portfolio/before-after-hd-makeover.jpg",
    category: "makeup",
    ctaText: "Book Airbrush",
  },
  {
    _id: "65a000000000000000000006",
    title: "Engagement & Reception Glam",
    price: "From ₹7,999",
    description: "Customized soft glam for evening reception and engagement functions.",
    imageUrl: "/images/portfolio/bridal-pink-saree-gold-jewellery.jpg",
    category: "makeup",
    ctaText: "Book Reception Glam",
  },
  {
    _id: "65a000000000000000000007",
    title: "Guest & Family Makeup",
    price: "From ₹999",
    description: "Party makeover and touch-ups for family members and bridesmaids.",
    imageUrl: "/images/portfolio/traditional-south-indian-bride.jpg",
    category: "makeup",
    ctaText: "Book Guest Makeup",
  },
  // Hair & Saree
  {
    _id: "65a000000000000000000008",
    title: "South Indian Mogra Gajra Jada",
    price: "From ₹2,500",
    description: "Classic fresh floral braid extensions and traditional hair artistry.",
    imageUrl: "/images/portfolio/traditional-south-indian-bride.jpg",
    category: "hairstyle",
    ctaText: "Book Hairstyle",
  },
  {
    _id: "65a000000000000000000009",
    title: "French Bubble Pearl Braid",
    price: "From ₹3,000",
    description: "Modern braided crown with pearl pins and crystal accessories.",
    imageUrl: "/images/portfolio/bridal-close-up-portrait.jpg",
    category: "hairstyle",
    ctaText: "Book Modern Hairstyle",
  },
  {
    _id: "65a000000000000000000010",
    title: "Temple Silver Choti Medallions",
    price: "From ₹2,000",
    description: "Traditional coin medallion hair jewellery styling and thick braid.",
    imageUrl: "/images/portfolio/traditional-south-indian-bride.jpg",
    category: "hairstyle",
    ctaText: "Book Temple Hairdo",
  },
  {
    _id: "65a000000000000000000011",
    title: "Saree Box Pleating & Folding",
    price: "From ₹800",
    description: "Iron pressing and pre-pleating for hassle-free drape on wedding day.",
    imageUrl: "/images/portfolio/full-bridal-pose-silk-saree.jpg",
    category: "saree",
    ctaText: "Book Saree Draping",
  },
  // Jewellery & Rentals
  {
    _id: "65a000000000000000000012",
    title: "Antique Jewellery Rental",
    price: "From ₹1,200",
    description: "Temple gold, antique chokers, and ottiyanam waist belts for bridal functions.",
    imageUrl: "/images/jewellery/antique-bridal-complete-set.jpg",
    category: "jewellery",
    ctaText: "Explore Rentals",
  },
  {
    _id: "65a000000000000000000013",
    title: "Bridal & Guest Mehendi",
    price: "From ₹1,500",
    description: "Customized intricate organic henna designs for bride and guests.",
    imageUrl: "/images/portfolio/before-after-hd-makeover.jpg",
    category: "mehendi",
    ctaText: "Book Mehendi",
  },
  {
    _id: "65a000000000000000000014",
    title: "Studio Trial & Matching Session",
    price: "From ₹999",
    description: "Personalized saree drape and foundation shade matching consultation at studio.",
    imageUrl: "/images/portfolio/bridal-close-up-portrait.jpg",
    category: "other",
    ctaText: "Book Studio Trial",
  },
  {
    _id: "65a000000000000000000015",
    title: "Outstation Travel Team",
    price: "Contact Us",
    description: "Senior styling team available across Salem, Tamil Nadu, Bangalore and South India.",
    imageUrl: "/images/portfolio/bridal-pink-saree-gold-jewellery.jpg",
    category: "other",
    ctaText: "Inquire Travel Team",
  },
];

export const INITIAL_TESTIMONIALS = [
  {
    _id: "65c000000000000000000001",
    customerName: "Priya & Karthik",
    review: "Maha Shree ma'am created the absolute bridal look of my dreams! The HD makeup lasted all day through heat and tears without cracking or getting shiny.",
    rating: 5,
    isFeatured: true,
    isDeleted: false,
  },
  {
    _id: "65c000000000000000000002",
    customerName: "Ananya R.",
    review: "The saree draping precision and hair styling for my Muhurtham were flawless. Every relative complimented my look. SKM is the best in Salem!",
    rating: 5,
    isFeatured: true,
    isDeleted: false,
  },
  {
    _id: "65c000000000000000000003",
    customerName: "Deepika S.",
    review: "I took the Royal Airbrush Bridal Package. Truly felt like royalty on my reception night! Highly recommend Maha Shree for all brides.",
    rating: 5,
    isFeatured: true,
    isDeleted: false,
  },
];

export const INITIAL_GALLERY_ITEMS = [
  {
    _id: "65b000000000000000000001",
    imageUrl: "/images/portfolio/before-after-hd-makeover.jpg",
    altText: "HD Bridal Makeover Transformation by Maha Shree",
    category: "Before & After",
  },
  {
    _id: "65b000000000000000000002",
    imageUrl: "/images/portfolio/traditional-south-indian-bride.jpg",
    altText: "Outdoor Traditional South Indian Bride Look",
    category: "Bridal",
  },
  {
    _id: "65b000000000000000000003",
    imageUrl: "/images/portfolio/bridal-pink-saree-gold-jewellery.jpg",
    altText: "Royal Pink Silk Bridal Makeup & Antique Gold",
    category: "Bridal",
  },
  {
    _id: "65b000000000000000000004",
    imageUrl: "/images/portfolio/full-bridal-pose-silk-saree.jpg",
    altText: "Pre-Pleated Silk Saree & Temple Belt Pose",
    category: "Reception",
  },
  {
    _id: "65b000000000000000000005",
    imageUrl: "/images/portfolio/bridal-close-up-portrait.jpg",
    altText: "Glowing HD Bridal Portrait & Soft Hairdo by Maha Shree",
    category: "Hairstyle",
  },
  {
    _id: "65b000000000000000000006",
    imageUrl: "/images/jewellery/antique-bridal-complete-set.jpg",
    altText: "Royal Antique Temple Gold Grand Set Styling",
    category: "Jewellery",
  },
  {
    _id: "65b000000000000000000007",
    imageUrl: "/images/jewellery/lakshmi-haram-full-set.jpg",
    altText: "Lakshmi Haram Full Bridal Jewellery Set",
    category: "Jewellery",
  },
  {
    _id: "65b000000000000000000008",
    imageUrl: "/images/jewellery/peacock-antique-bridal-set.jpg",
    altText: "Peacock Motif Antique Bridal Set & Armlet",
    category: "Jewellery",
  },
  {
    _id: "65b000000000000000000009",
    imageUrl: "/images/jewellery/bride-wearing-jewellery.jpg",
    altText: "Engagement Soft Glam & Blue Silk Saree Styling",
    category: "Jewellery",
  },
  {
    _id: "65b000000000000000000010",
    imageUrl: "/images/portfolio/bridal-pink-saree-gold-jewellery.jpg",
    altText: "Muhurtham Saree Box Pleating & Fresh Gajra Jada",
    category: "Hairstyle",
  },
  {
    _id: "65b000000000000000000011",
    imageUrl: "/images/portfolio/traditional-south-indian-bride.jpg",
    altText: "Classic Red Muhurtham Makeover with Flower Jada",
    category: "Bridal",
  },
  {
    _id: "65b000000000000000000012",
    imageUrl: "/images/portfolio/before-after-hd-makeover.jpg",
    altText: "Flawless HD Base & Eye Artistry Transformation",
    category: "Before & After",
  },
];

export const INITIAL_FAQS = [
  {
    _id: "65e000000000000000000001",
    question: "How far in advance should I book my bridal makeover?",
    answer: "We recommend booking 3 to 6 months prior to your wedding date to secure your date, especially during peak marriage seasons in Tamil Nadu.",
    order: 1,
  },
  {
    _id: "65e000000000000000000002",
    question: "Do you travel to venues outside Salem?",
    answer: "Yes! Lead artist Maha Shree and our senior styling team travel across Tamil Nadu, Bangalore, and South India for outstation weddings.",
    order: 2,
  },
];
